### ISSUE TITLE
Invisible quest in inventory UI

### ISSUE THREAD

**Issue by AtzaMan** [ToroCraft/Dailies#48] opened 2017-05-10 17:58 UTC
Visible on hovering, even when disabled or abandoned.
Farming Valley modpack 0.7.6.
Bailies Dailies 6 for 1.10.2
https://drive.google.com/uc?export=view&id=0B23nTMZmrHpVSjV2MTlJX0JOTTA

**Comment by pandapaul** [comment] 2017-05-14 22:46
Duplicate of #37.  Always good to have more info though.  Thanks for reporting. :)

**Closed as completed by pandapaul** 2017-05-14 22:46 UTC
